version: '3'
services:
  prom:
    image: prom/prometheus
    volumes:
      - "./config:/etc/prometheus"
    command: "--config.file=/etc/prometheus/conf.yml"    
    ports: 
      - "9090:9090"
  grafana: 
    image: bitnami/grafana
    ports:
      - "3000:3000"
    volumes: 
      - "./grafana:/opt/bitnami/grafana/data"
  blackbox:
    image: prom/blackbox-exporter
    command: "--config.file=/config/blackbox.yml"
    volumes:
      - "./blackbox:/config/"
  ping: 
    image: prom/blackbox-exporter
    command: "--config.file=/config/blackbox.yml"
    volumes:
      - "./ping:/config/"
